# Generated by Django 4.2.7 on 2025-01-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_passport',
            field=models.IntegerField(blank=True, null=True, verbose_name='айди паспорт'),
        ),
    ]
