# Generated by Django 4.2.7 on 2025-01-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='created_at',
        ),
        migrations.AddField(
            model_name='route',
            name='additional_points',
            field=models.JSONField(blank=True, null=True, verbose_name='Дополнительные пути'),
        ),
        migrations.AddField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
