# Generated by Django 4.2.7 on 2025-01-24 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0003_alter_route_user_route2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forparents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='route2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forkids', to=settings.AUTH_USER_MODEL),
        ),
    ]
