# Generated by Django 4.2.7 on 2025-01-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_daily_history_weekly_delete_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='date',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
    ]
