# Generated by Django 4.2.7 on 2025-01-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_remove_history_date_remove_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='time_choice',
            field=models.CharField(choices=[('сегодня', 'сегодня'), ('вчера', 'вчера'), ('7 дней назад', '7 дней назад'), ('месяц назад', 'месяц назад'), ('6 месяцев назад', '6 месяцев назад')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
